name: Release Go Binary

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for version calculation

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Calculate Version
      id: version
      run: |
        # Get the latest tag
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        
        # Extract the version numbers
        IFS='.' read -r major minor patch <<< "${latest_tag#v}"
        
        # Increment patch version
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"
        
        echo "New version will be: $new_version"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
    
    - name: Update Go Dependencies
      run: |
        # Initialize at root level for all packages
        go mod tidy
    
    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-X main.Version=${{ steps.version.outputs.new_version }}" -o ./dist/tgs-windows-amd64.exe ./cmd/tgs
        
        # Build for Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Version=${{ steps.version.outputs.new_version }}" -o ./dist/tgs-linux-amd64 ./cmd/tgs
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.Version=${{ steps.version.outputs.new_version }}" -o ./dist/tgs-darwin-amd64 ./cmd/tgs
        GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.Version=${{ steps.version.outputs.new_version }}" -o ./dist/tgs-darwin-arm64 ./cmd/tgs

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.new_version }}
        name: Release ${{ steps.version.outputs.new_version }}
        files: |
          ./dist/tgs-windows-amd64.exe
          ./dist/tgs-linux-amd64
          ./dist/tgs-darwin-amd64
          ./dist/tgs-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          Automated release from main branch
          
          This release includes all changes merged to the main branch.
          
          ### Binaries
          - Windows (64-bit): tgs-windows-amd64.exe
          - Linux (64-bit): tgs-linux-amd64
          - macOS (Intel): tgs-darwin-amd64
          - macOS (Apple Silicon): tgs-darwin-arm64 