name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Update Go Dependencies
      run: |
        cd tgs/cmd
        go mod init github.com/davoodharun/terragrunt-scaffolder/tgs/cmd
        go mod tidy
    
    - name: Build binaries
      run: |
        mkdir -p dist
        cd tgs/cmd
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -o ../../dist/tgs-windows-amd64.exe .
        
        # Build for Linux
        GOOS=linux GOARCH=amd64 go build -o ../../dist/tgs-linux-amd64 .
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -o ../../dist/tgs-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o ../../dist/tgs-darwin-arm64 .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/tgs-windows-amd64.exe
          ./dist/tgs-linux-amd64
          ./dist/tgs-darwin-amd64
          ./dist/tgs-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true 